<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => 'Cheers!',
  'key' => 'tac',
  'author' => 'Taction Software LLC',
  'description' => 'SuiteCRM Twilio SMS Service',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'SuiteCRM Twilio SMS Service',
  'published_date' => '2018-01-19 13:15:25',
  'type' => 'module',
  'version' => 1513235725,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'SuiteCRM_TwilioSMS_Service',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'tac_sms_templates',
      'class' => 'tac_sms_templates',
      'path' => 'modules/tac_sms_templates/tac_sms_templates.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'tac_inbound_message',
      'class' => 'tac_inbound_message',
      'path' => 'modules/tac_inbound_message/tac_inbound_message.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/tac_sms_templates',
      'to' => 'modules/tac_sms_templates',
    ),
    1 => 
    array (
      'from' => '<basepath>/custom/include/twilio-php-master',
      'to' => 'custom/include/twilio-php-master',
    ),
    2 => 
    array (
      'from' => '<basepath>/custom/modules/AOW_WorkFlow/controller.php',
      'to' => 'custom/modules/AOW_WorkFlow/controller.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/custom/modules/AOW_Actions/actions/actionSendSMS.php',
      'to' => 'custom/modules/AOW_Actions/actions/actionSendSMS.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/custom/modules/AOW_Actions/actions/actionSendSMS.js',
      'to' => 'custom/modules/AOW_Actions/actions/actionSendSMS.js',
    ),
    5 => 
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.SMS_Type_list.php',
      'to' => 'custom/Extension/application/Ext/Language/en_us.SMS_Type_list.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/custom/Extension/modules/AOW_Actions/Ext/Actions/actions.php',
      'to' => 'custom/Extension/modules/AOW_Actions/Ext/Actions/actions.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/custom/Extension/modules/AOW_Actions/Ext/Language/en_us.twilio_lang.php',
      'to' => 'custom/Extension/modules/AOW_Actions/Ext/Language/en_us.twilio_lang.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/custom/Extension/modules/Administration/Ext/Administration/tac_twilio_admin_panel.php',
      'to' => 'custom/Extension/modules/Administration/Ext/Administration/tac_twilio_admin_panel.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/custom/Extension/modules/Administration/Ext/Language/en_us.tac_twilio_language.php',
      'to' => 'custom/Extension/modules/Administration/Ext/Language/en_us.tac_twilio_language.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/custom/modules/Administration/tac_twilio_config.php',
      'to' => 'custom/modules/Administration/tac_twilio_config.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/custom/modules/Administration/tac_twilio_config.tpl',
      'to' => 'custom/modules/Administration/tac_twilio_config.tpl',
    ),
    12 =>
    array (
		'from' => '<basepath>/custom/Extension/application/Ext/EntryPointRegistry/tac_sms_template_getFields_entryPoint.php',
		'to' => 'custom/Extension/application/Ext/EntryPointRegistry/tac_sms_template_getFields_entryPoint.php',
    ),
    13 =>
    array (
		'from' => '<basepath>/custom/modules/tac_sms_templates/logic_hooks.php',
		'to' => 'custom/modules/tac_sms_templates/logic_hooks.php',
    ),
    14 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/RedirectDetail.php',
		'to' => 'modules/tac_sms_templates/RedirectDetail.php',
    ),
    15 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/views/view.detail.php',
		'to' => 'modules/tac_sms_templates/views/view.detail.php',
    ),
    16 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/views/view.edit.php',
		'to' => 'modules/tac_sms_templates/views/view.edit.php',
    ),
    17 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/metadata/editviewdefs.php',
		'to' => 'modules/tac_sms_templates/metadata/editviewdefs.php',
    ),
    18 =>
    array (
		'from' => '<basepath>/Twilio.log',
		'to' => 'Twilio.log',
    ),
    19 =>
    array (
		'from' => '<basepath>/custom/modules/Administration/tac_twilio_log_view.php',
		'to' => 'custom/modules/Administration/tac_twilio_log_view.php',
    ),
    20 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/vardefs.php',
		'to' => 'modules/tac_sms_templates/vardefs.php',
    ),
    21 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/get_fields.php',
		'to' => 'modules/tac_sms_templates/get_fields.php',
    ),
    22 =>
    array (
		'from' => '<basepath>/custom/Extension/application/Ext/LogicHooks/TACTION_twilio_module_action_hook.php',
		'to' => 'custom/Extension/application/Ext/LogicHooks/TACTION_twilio_module_action_hook.php',
    ),
    23 =>
    array (
		'from' => '<basepath>/custom/Extension/application/Ext/EntryPointRegistry/TactionTwilioSendSMSModuleView.php',
		'to' => 'custom/Extension/application/Ext/EntryPointRegistry/TactionTwilioSendSMSModuleView.php',
    ),
    24 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/SendSMSFromModuleView.php',
		'to' => 'modules/tac_sms_templates/SendSMSFromModuleView.php',
    ),
    25 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/SendSMSFromModuleViewAction.php',
		'to' => 'modules/tac_sms_templates/SendSMSFromModuleViewAction.php',
    ),
    26 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/js/sms_module_action.js',
		'to' => 'modules/tac_sms_templates/js/sms_module_action.js',
    ),
    27 =>
    array (
		'from' => '<basepath>/modules/tac_sms_templates/smsTemplatePopup.php',
		'to' => 'modules/tac_sms_templates/smsTemplatePopup.php',
    ), 
    28 => 
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/EntryPointRegistry/taction_twilio_message_statusCallBack.php',
      'to' => 'custom/Extension/application/Ext/EntryPointRegistry/taction_twilio_message_statusCallBack.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/modules/tac_inbound_message',
      'to' => 'modules/tac_inbound_message',
    ),
	30 => array (
		'from' => '<basepath>/custom/Extension/application/Ext/EntryPointRegistry/TactionTwilioReceiveSMS.php',
		'to' => 'custom/Extension/application/Ext/EntryPointRegistry/TactionTwilioReceiveSMS.php',
	),
	31 => array (
		'from' => '<basepath>/custom/include/twilio-php-master/receive_sms.php',
		'to' => 'custom/include/twilio-php-master/receive_sms.php',
	),
	32 => array (
		'from' => '<basepath>/custom/include/twilio-php-master/sendsmsFromSchedular.php',
		'to' => 'custom/include/twilio-php-master/sendsmsFromSchedular.php',
	),
	33 => array (
		'from' => '<basepath>/custom/Extension/modules/Schedulers/Ext/ScheduledTasks/twilio_sms_scheduler.php',
		'to' => 'custom/Extension/modules/Schedulers/Ext/ScheduledTasks/twilio_sms_scheduler.php',
	),
	34 => array (
		'from' => '<basepath>/custom/Extension/modules/Schedulers/Ext/Language/en_us.twilio_sms_scheduler.php',
		'to' => 'custom/Extension/modules/Schedulers/Ext/Language/en_us.twilio_sms_scheduler.php',
	),
	35 => array (
		'from' => '<basepath>/custom/include/twilio-php-master/statusCallback.php',
		'to' => 'custom/include/twilio-php-master/statusCallback.php',
	),
	36 => array (
		'from' => '<basepath>/custom/modules/Administration/TwilioLog.php',
		'to' => 'custom/modules/Administration/TwilioLog.php',
	),
	37 => array (
		'from' => '<basepath>/custom/Extension/application/Ext/EntryPointRegistry/TactionTwilioTwilioLog.php',
		'to' => 'custom/Extension/application/Ext/EntryPointRegistry/TactionTwilioTwilioLog.php',
	),
	38 => array (
		'from' => '<basepath>/scripts/post_install.php',
		'to' => 'cache/upgrades/temp/post_install.php',
	),
	// license directory
	39 => array (
		'from' => '<basepath>/license',
        'to' => 'modules/tac_sms_templates',
	),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from'=> '<basepath>/license_admin/language/en_us.SuiteCRM_TwilioSMS_Service.php', // <-- CHANGE NAME HERE
      'to_module'=> 'Administration',
      'language'=>'en_us'
    ),
  ),
  'administration' =>
    array(
		array(
			'from'=>'<basepath>/license_admin/menu/SuiteCRM_TwilioSMS_Service_admin.php', 
			'to' => 'modules/Administration/SuiteCRM_TwilioSMS_Service_admin.php', 
		),
	),
	'action_view_map' =>
	array (
		array(
			'from'=> '<basepath>/license_admin/actionviewmap/SuiteCRM_TwilioSMS_Service_actionviewmap.php', // <-- CHANGE NAME HERE
			'to_module'=> 'tac_sms_templates', // <-- CHANGE NAME HERE - To your module name
		),
	),
  'post_uninstall' => array(0 => '<basepath>/post_uninstall.php',),
);
